### ISSUE TITLE
Crash when joining EMC while queue is paused

### ISSUE THREAD

**Issue by Kieubasiarz** [Warriorrrr/EarthMCEssentials#3]
Version: 1.16.4 and 1.16.5
Client: MultiMC
No other non-essential mods besides fabric api. Latest versions.
[Crash report for 1.16.5](https://pastebin.com/zrVk9Fpm)

When joining the server, "Joining world" turns into "Saving game" in a second.
The queue was paused in that time, so it may be a cause. It previously worked fine.
Crash was replicable. Latest.log shows a split second of motd and queue chat before crash. Other servers work fine.

**Comment by Warriorrrr** [comment]
Likely fixed by now, let me know if this is still happening for you on the latest version.
