### ISSUE TITLE
Crashes on launch 

### ISSUE THREAD

**Issue by benbenyatta** [Warriorrrr/EarthMCEssentials#9]
I get the same crash screen as all the other dudes do
EMCEssentials version: 2.0.1
fabric api: 0.53.4
fabric loader: 0.14.6

crash: screen https://i.imgur.com/NyhJJaf.png
crash only happens with this version of EMCE, the 1.17.1 lets me launch the game

**Comment by Owen3H** [comment]
EMCE is built on 0.48 Fabric API, 0.50 or higher will be supported in a future version.

Edit: #10 Should fix this in the next release.
